version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "goodway"
      DB_MYSQL_PASSWORD: "Guwei888"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'Guwei888Guwei888Guwei888'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'goodway'
      MYSQL_PASSWORD: 'Guwei888'
    volumes:
      - ./data/mysql:/var/lib/mysql
